name: Firebase Deploy

on:
  push:
    branches:
      - main  # Replace with your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Use the Node.js version compatible with your project

    # Step 3: Install project dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the application
    - name: Build the app
      run: npm run build # Ensure this matches your project's build command

    # Step 5: Authenticate Firebase CLI using a service account key
    - name: Authenticate Firebase CLI
      env:
        GOOGLE_APPLICATION_CREDENTIALS: firebase-key.json
      run: |
        echo "${{ secrets.NETFLIX_GPT_FIREBASE_REPO_SECRET }}" > firebase-key.json

    # Step 6: Install Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Step 7: Deploy to Firebase Hosting
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting
