name: Firebase Deploy

on:
  push:
    branches:
      - main  # Replace with your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Use the Node.js version compatible with your project

    # Step 3: Install project dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the application
    - name: Build the app
      run: npm run build # Ensure this matches your project's build command

    # Step 5: Install Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Step 6: Deploy to Firebase Hosting using Firebase Token
    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Use your token stored in GitHub Secrets
      run: firebase deploy --only hosting
